#!/bin/bash

# Image paths
morning="/home/legostax/.config/awesome/wallpapers/morning.png"
day="/home/legostax/.config/awesome/wallpapers/day.png"
evening="/home/legostax/.config/awesome/wallpapers/evening.jpg"
night="/home/legostax/.config/awesome/wallpapers/night.jpg"

# Code
sleep 0.25
time=$(date "+%T">&1)
hour=${time:0:2}

# Morning: 05-08; Day: 09-03; Evening: 04-06; Night: 07-04
if [ "$hour" = "05" ] || [ "$hour" = "06" ] || [ "$hour" = "07" ] || [ "$hour" = "08" ]; then
	feh --bg-fill $morning
elif [ "$hour" = "09" ] || [ "$hour" = "10" ] || [ "$hour" = "11" ] || [ "$hour" = "12" ] || [ "$hour" = "13" ] || [ "$hour" = "14" ] || [ "$hour" = "15" ]; then
	feh --bg-fill $day
elif [ "$hour" = "16" ] || [ "$hour" = "17" ] || [ "$hour" = "18" ]; then
	feh --bg-fill $evening
elif [ "$hour" = "19" ] || [ "$hour" = "20" ] || [ "$hour" = "21" ] || [ "$hour" = "22" ] || [ "$hour" = "23" ] || [ "$hour" = "00" ] || [ "$hour" = "01" ] || [ "$hour" = "02" ] || [ "$hour" = "03" ] || [ "$hour" = "04" ]; then
	feh --bg-fill $night
fi
